// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nelfazrpdniflxuwuqjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lbGZhenJwZG5pZmx4dXd1cWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4OTA1NDksImV4cCI6MjA1NzQ2NjU0OX0.HlDfd92HiJjUQf3Y21wke8K9VXMw5Fz6f6beHkfuayM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);